### ISSUE TITLE
Problem with Log Viewer

### ISSUE THREAD

**Issue by ahmad-kassem** [offer-shmuely/edgetx-x10-scripts#1]
Hello
I installed the LogViewer on my TX16S and when i try to open it i get an error message: attempt to call field 'dir' (a nil value)
Kindly advise how to solve this.

Regards
Ahmad

**Comment by offer-shmuely** [comment]
Did you put it under /scripts/tools ?
Dis you copy also the LogViewer directory?

**Comment by offer-shmuely** [comment]
Waiting for more info,
Please also try the new version

**Comment by ahmad-kassem** [comment]
> Did you put it under /scripts/tools ? Dis you copy also the LogViewer directory? what edgeTx? 2.7.1?

it worked on EdgeTx but did not work on OpenTx, i will try the new version and let you know.
Thanks for the Lua, I like it.

**Comment by offer-shmuely** [comment]
It is NOT supposed to work on openTx
It use new api that does not exist on openTx, and no one is developing it anymore, so no one adding them.
It is intended only for edgeTx 2.7 and above.
