### ISSUE TITLE
Log file "not found" but there is a CSV and logs files

### ISSUE THREAD

**Issue by NikosSprocket** [offer-shmuely/edgetx-x10-scripts#10]
I am running EdgeTX v2.8.3 on a TX16S and the LogViewer 1.1 is not working anymore.

The Lua runs, then is a "flash" of the Analysis screen and then the log selection screen shows with a header "/LOGS/not found".

The interesting part is that I can pick the Model and the date of the actual file but the Log file entry shows "not found".

I have removed the existing LogViewer.lua/luac, the LogViewer dir. and cleared in the /LOGS all logs and csv file. Downloaded from Github a "fresh" copy and put them in the proper place /SCRIPTS/TOOLS. Have the TX create a log file and then run the LogViewer. Same behavior. 
![20230509_230026](https://github.com/offer-shmuely/edgetx-x10-scripts/assets/90818362/255edb11-e5b4-4e70-9d36-29c8292ec700)
![20230509_230056](https://github.com/offer-shmuely/edgetx-x10-scripts/assets/90818362/22e1bb56-e436-4900-a03a-7af7dbd2ff16)

I also tried to collect some info. by:
local ENABLE_LOG_TO_CONSOLE =  false
local ENABLE_LOG_TO_FILE    = true

but never generated the app.log file.

**Comment by NikosSprocket** [comment]
Today, I had two sort test flights, 2 and 4 minutes  each, and this time the Log Viewer worked. There was a small pause at the initial screen and then went to the log analyzer and after analyzing the 2 files moved to the log selection. The graphs looked great too. The app.log was 

I will leave it as is and keep testing it. Put more notes when I have more information.

I did not mentioned before but the issues I had before where from running the quad on the bench-top. Mostly arming/disarming but no flight; just spinning the props at low RPMs.

**Comment by offer-shmuely** [comment]
Hi
that is normal, 
to reduce the "real logs" from testing on the banch, and from arming and disarming with no flights, 
the log viewer ignore any log file that is less than 60 second, 
and also ignore any log file that all the telemetry was without any change, (well there is no point to show a graph of straight lines)
please take a look on the csv log, and check if the logs you are trying to view, is less than/ or grater than 60seconds

**Comment by NikosSprocket** [comment]
Hi Offer!
That's great putting the extra effort to make the lua "smart" and ignore mostly trivial data. All the logs that where ignored were less than 60 sec. and the quadcopter just sitting on the bench connected via USB to the FC. I run Arducopter and used to getting logs even when the quad just sitting on the bench!

One suggestion I will make will be to put one sentence in the Wiki informing the OSD users that will not be logs during inactivity and less than 60 sec.  lol

Anyway, your lua is absolutely awesome and thank you for creating it!

**Comment by offer-shmuely** [comment]
Good idea
Added
