### ISSUE TITLE
LView.lua fails to find a recent Model but there are 5 present

### ISSUE THREAD

**Issue by jwcalvert** [offer-shmuely/edgetx-x10-scripts#11]
I have at least 5 files with filename base  Timber X-2023-05-21-201053.
I am testing inside the EdgeTX Companion Simulator.

My Taranis is B/W.  Will the script run?
Is this script meant to run on EdgeTX on a Taranis 9D+ as in my situation?

Thanks

**Comment by offer-shmuely** [comment]
LView.lua is not my script, 
I can not answer this for someone else.
If you are asking on LogViewer.lua, than the answer is: I wrote it only for color screens

**Comment by jwcalvert** [comment]
Hello Offer,

Thanks for your speedy reply.

I will figure it out.
