### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by wookie457** [offer-shmuely/edgetx-x10-scripts#3]
I have just installed logviewer.lua and logviewer directory to the script/tools on a tx16s edge version 2.71. I am getting a script syntax error of  "TOOLS/Logviewer.lua:139: attempt to call field 'getVer' (a nil value)"

**Comment by offer-shmuely** [comment]
did you copy this dir?
/SCRIPTS/TOOLS/LogViewer

**Comment by wookie457** [comment]
Yes, i put the logviewer.lua and the entire logviewer folder into the SCRIPTS/TOOLS on the sd card. should they all be in the same logviewer folder in the SCRIPTS/TOOLS directory
![sdcard](https://user-images.githubusercontent.com/57927112/200141488-ada69ac8-d819-4089-8e34-f0648606b9d8.png)

**Comment by offer-shmuely** [comment]
can you show the LogViewer directory?

**Comment by wookie457** [comment]
here you go
![logviewer](https://user-images.githubusercontent.com/57927112/200145084-ebab4012-26b1-40bd-8f24-06bace6b2581.png)

**Comment by offer-shmuely** [comment]
well, I see the issue
please update this file:
https://github.com/offer-shmuely/edgetx-x10-scripts/blob/main/SCRIPTS/TOOLS/LogViewer/libgui.lua

**Comment by wookie457** [comment]
You sir are awesome! It is now working. I take it you dont need the file from the old version?
