### ISSUE TITLE
LogViewer

### ISSUE THREAD

**Issue by Dave-thirteen** [offer-shmuely/edgetx-x10-scripts#5]
Hi there Offer,

I'm trying to run your log viewer on a TX16S.
Firstly will it work on this TX?

I have two lua scripts that I downloaded - V1.1 and V3
With V1.1 the script runs and allows me to select a model and date but in the Log file field says "not found"

With V3 I get an error when running the script.
TOOLS/LogViewer/LogViewer3.lua:152 attempt to index local 'm_libguiu' (a nil value)

Am I missing a file or have I set things up incorrectly?

If you can, I would appreciate you emailing me a zip file with the files I need, or letting me know where I can find them on GitHub.

I'm not experienced in using GH, so would appreciate your help!

Thanks

Dave.

**Comment by offer-shmuely** [comment]
yes, the logviewer will work on RadioMaster 16, as long as it have EdgeTx 2.7 and above
you should not run the LogViewer3.lua
you need to run the /SCRIPTS/TOOLS/LogViewer.lua, it is the script that outside the directory

go to this page:
https://github.com/offer-shmuely/edgetx-x10-scripts

and the on the green "code" button, and download as zip


![image](https://user-images.githubusercontent.com/7026911/223589293-82ef2842-4e13-4a13-b318-124d7cada718.png)

**Comment by offer-shmuely** [comment]
any news?

**Comment by Dave-thirteen** [comment]
Offer,
Sorry for my very late reply.

I have got the viewer working well on my TX16S with the latest EdgeTX.

I found I had two problems - one was that I had a Lua script that had
version 3 in its heading and that just froze the screen.
When I ran the version with 1.11 in its touch button that also seemed not
to work.

My mistake - sorry!

In my eagerness to try the viewer I had put on a couple of log files that
OpenTX had created and tried to view them.

It was only much later that I deleted the OpenTX files and by that time I
had a couple of EdgeTX files on my TX16s.
Of course they worked as hoped!
I then looked carefully at both file structures and noticed that the EdgeTX
version had more fields and they were in a different order to those created
by OpenTX.

Your script now works well and I can see you have put a lot of effort into
it - well doner and THANKS!

As in many cases it was "operator error", at least it wasn't "pilot error"!

Kind regards

Dave#13

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by offer-shmuely** [comment]
Does the openTx log are hanging the script, or it ignores them?

**Comment by Dave-thirteen** [comment]
Offer the viewer sees the files from the OpenTX telemetry but does not
allow them to be read.

It ignores them and does not hang.

Thanks and kind regards
73
Dave
G3ZGZ

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
