### ISSUE TITLE
Logviewer on TX16s and 2.9 nightly stuck at entry screen

### ISSUE THREAD

**Issue by mha1** [offer-shmuely/edgetx-x10-scripts#7]
... and the entry screen looks odd. Check out the white lines

![image](https://user-images.githubusercontent.com/5615068/224482153-fa05197a-e6b0-496e-8cd4-ab485f6ad8ee.png)

**Comment by offer-shmuely** [comment]
in the logviewer directory, there is a file named "lib_log.lua"
open it in editor (notpad), 
change on line 4 from false to true
local ENABLE_LOG_TO_FILE    = true
run the logviewer script,
and send me back the file that will be generated at
/SCRIPTS/TOOLS/LogViewer/app.log

**Comment by mha1** [comment]
```
local app_name, script_dir = ...

local ENABLE_LOG_TO_CONSOLE = false
local ENABLE_LOG_TO_FILE    = true
...
```

It doesn't even create app.log. It's stuck at the initial screen above (EdgeTX one of the most recent nightlys). Did you take note of the strange white lines?

**Comment by offer-shmuely** [comment]
is that still happening?

**Comment by offer-shmuely** [comment]
I checked on my computer on today 
it works on the nightly build
so, I need more details what happen on your computer

**Comment by offer-shmuely** [comment]
Still happen?

**Comment by mha1** [comment]
Hi Offer, Sorry I didn't follow up on this issue. Fair to close. I'll pop back in eventually.
