### ISSUE TITLE
LogViewer 1.11 Tx16S  v2.8.1

### ISSUE THREAD

**Issue by VectorV3** [offer-shmuely/edgetx-x10-scripts#8]
When trying to load graph I get error msg. 

Script syntax error
TOOLS/LogViewer/LogViewer3.lua:180 bad argument #1 to 'seek' (FILE*expected , got nil)

also can't select model must choose All otherwise if I choose model there are no log files to pick from.  Logs  made by EdgeTX.

**Comment by offer-shmuely** [comment]
also, please send a video of the problem

**Comment by VectorV3** [comment]
@offer-shmuely 
Hello. 
Thanks, somehow I got this working. I have had several log files from same model , i did delete all short files ( 15 to 30 sec long) and did put fresh LogViewer dir and .luas cript in TOOLS folder. All working now. I can select model , date and file.  Thanks again . Great LogViewer :) now I know I need to put extra cap on my Fbl system.

**Comment by offer-shmuely** [comment]
how did you see that you need an extra cap?

**Comment by VectorV3** [comment]
Thanks to LogViewer I noticed how often voltage drop occur in flight controller / RX. during flight.  Hopefully extra cap will prevent this.
