### ISSUE TITLE
Does not show Logs

### ISSUE THREAD

**Issue by Chris3E** [offer-shmuely/edgetx-x10-scripts#9]
Hi,

tried it today made a testlog today(10s). I see it in explorer under LOGS folder.

But when I open LogView, i can select model, I can select date of today but und Log file it shows "not found"

The Logfile was created with FrSky G-RX8 w/ onboard vario.

Attached files of my Logs folder:
[E5-2023-04-21-170518.csv](https://github.com/offer-shmuely/edgetx-x10-scripts/files/11297290/E5-2023-04-21-170518.csv)
[log-viewer.csv](https://github.com/offer-shmuely/edgetx-x10-scripts/files/11297291/log-viewer.csv)

Thanks a lot in advance!

Christoph

Using RM TX16s / EdgeTX v2.8.2

**Comment by Chris3E** [comment]
Was at the fiel today and took a flight log. Tool shows both logs and works perfect. Thanks

**Comment by offer-shmuely** [comment]
To remove useless data, the log viewer show only flight above 60seconds
I with that logs below 60sec was not recorded in the first place, but is the behavior currently
